package framework;

public enum ObjectId {
	
	Player(),
	Block(),
	PlayerClimbAnimation(),
	DustAnimation(),
	VerticalDustAnimation(),
	AttackAnimation(),
	ShooterTrap(),
	ChangingShooterTrap(),
	ArrowProjectile(),
	BallProjectile(),
	
	Water(),
	Bullet(),
	BulletPopAnimation(),
	BasicEnemy(),
	BasicEnemyDeath(),
	SpiderEnemy(),
	PressEnemy(),
	ShooterEnemy(),
	LeftShooterEnemy(),
	GhostEnemy(),
	ShooterEnemyBullet(),
	LeftShooterEnemyBullet(),
	InvBlock(),
	HUD(),
	Flag(),
	hpUp(),
	Coin(),
	Flower(),
	Flower2(),
	Shop(),
	Spike(),
	BloodySpike(),
	NoCollision(),
	Gems(),
	MeleeAttack(),
	SpikedShield(),
	Propeller(),
	PropellerStream(),
	PropellerStreamx5(),
	DirtBlock5x5(),
	Menu(),
	FirstBoss(),
	RedDoor(),
	RedKey(),
	BoomerangEnemy(),
	TeleportEntrance(),
	TeleportExit(),
	MovingPlatform(),
	Platform(),
	Trail(),
	FrogEnemy();
}
